/**:
  ros__parameters:
    imu_topic: "/converted/imu"
    laser_topic: "/lidar_points"
    sensor: "velodyne"
    use_imu_roll_pitch: false
    
    world_frame: "odom"
    world_frame_rot: "map_rot"
    sensor_frame: "base_footprint"
    sensor_frame_rot: "odom_rot"

    imu_acc_x_limit: 0.5
    imu_acc_y_limit: 0.2
    imu_acc_z_limit: 0.4

    # Feature Extraction Params
    feature_extraction_node:
        scan_line: 16
        min_range: 0.2    #<!-- remove too closed points -->
        filter_point_size: 3

    # Laser Mapping Params
    laser_mapping_node:
        mapping_line_resolution: 0.1
        mapping_plane_resolution: 0.2
        max_iterations: 5
        max_surface_features: 2000

        # For localization mode
        localization_mode: false         # If true, localization mode is enabled; otherwise, SLAM mode is used
        read_pose_file: false           # Set to true to read initial pose from a txt file
        init_x: 0.0                     # Initial X position for localization
        init_y: 0.0                     # Initial Y position for localization
        init_z: 0.0                     # Initial Z position for localization
        init_roll: 0.0                  # Initial roll angle
        init_pitch: 0.0                 # Initial pitch angle
        init_yaw: 0.0                   # Initial yaw angle

    # IMU Preintegration Params
    imu_preintegration_node:
        lidar_correction_noise: 0.01

        acc_n: 3.9939570888238808e-03       # accelerometer measurement noise standard deviation. #0.2
        gyr_n: 1.5636343949698187e-03       # gyroscope measurement noise standard deviation.     #0.05
        acc_w: 6.4356659353532566e-05       # accelerometer bias random work noise standard deviation.  #0.02
        gyr_w: 3.5640318696367613e-05       # gyroscope bias random work noise standard deviation.     #4.0e-5
        g_norm: 9.80511                     # 0 means you need to provide both imu-camera and laser-camera extrinsic

