pointcloud_to_laserscan:
  ros__parameters:
    qos_overrides:
      /scan:
        publisher:
          reliability: best_effort
          durability: volatile
          history: keep_last
          depth: 10

